# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Intervals Bot scheduler

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 4 * * *'
  push:
    branches: [ main, dev ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run Scheduled JOB
      env:
        INTERVALS_API_KEY: ${{ secrets.INTERVALS_API_KEY }}
        TEMPO_API_KEY: ${{ secrets.TEMPO_API_KEY }}
      run: |
        python run_timesheet.py